name: Run Gradle on puch to branch
on:
  push:
    branches:
      - build
jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      PUBLIC_MINELABS_KEY_ED: ${{ secrets.PUBLIC_MINELABS_KEY_ED }}
      PUBLIC_MINELABS_KEY_RSA: ${{ secrets.PUBLIC_MINELABS_KEY_RSA }}
      PRIVATE_MINELABS_KEY: ${{ secrets.PRIVATE_MINELABS_KEY }}
      PRIVATE_MINELABS_KEY_PUB: ${{ secrets.PRIVATE_MINELABS_KEY_PUB }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Test sftp
        run: |
          echo "stop stop" > restart
          rm -f id_rsa id_ed id_rsa.pub id_ed.pub
          echo ${{ secrets.PRIVATE_MINELABS_KEY }} > id_rsa_win
          tr -d '\015' <id_rsa_win >id_rsa
          echo $PRIVATE_MINELABS_KEY "test"
          cat id_rsa
          cat id_rsa_win
          echo "test"
          chmod 600 id_rsa
          #!echo $PRIVATE_MINELABS_KEY_PUB > "id_rsa.pub"
          sftp -o "StrictHostKeyChecking no" -P 2233 -i ./id_rsa minelabs@minelabs.be<< EOF
          cd config
          put restart
          get restart.log
          bye
          EOF
          cat restart.log
        shell: bash

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Move build to output
        run: ./.github/scripts/move_build.sh
        shell: bash

      - name: Upload to Minelabs-server
        run: ./.github/scripts/sftp_upload.sh
        shell: bash

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: mod
          path: output

