name: Run Gradle on puch to branch
on:
  push:
    branches:
      - build
jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      PUBLIC_MINELABS_KEY_ED: ${{ secrets.PUBLIC_MINELABS_KEY_ED }}
      PUBLIC_MINELABS_KEY_RSA: ${{ secrets.PUBLIC_MINELABS_KEY_RSA }}
      PRIVATE_MINELABS_KEY: ${{ secrets.PRIVATE_MINELABS_KEY}}
      $PRIVATE_MINELABS_KEY_PUB: ${{ secrets.$PRIVATE_MINELABS_KEY_PUB}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Move build to output
        run: ./.github/scripts/move_build.sh
        shell: bash

      - name: Upload to Minelabs-server
        run: ./.github/scripts/sftp_upload.sh
        shell: bash

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: mod
          path: output

